/**
 * Eurostat CN8 codelist HS chapter (2-digit) code -> English name, for the
 * ru-trade-timeline chart's category picker. One-time generated from the
 * same codelist scripts/comext-ru-chapter-scout.ts and
 * comext-ru-backfill.ts already fetch (their loadNomenclature/
 * loadChapterToCN8 build this exact map, just never persist it) -- fixed
 * nomenclature, not data that changes, so it's a checked-in constant
 * rather than an HTTP call at build time.
 */
export const HS_CHAPTER_NAMES: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat and edible meat offal",
  "03": "Fish and crustaceans, molluscs and other aquatic invertebrates",
  "04": "Dairy produce; Birds' eggs; Natural honey; Edible products of animal origin, not elsewhere specified or included",
  "05": "Products of animal origin, not elsewhere specified or included",
  "06": "Live trees and other plants; Bulbs, roots and the like; Cut flowers and ornamental foliage",
  "07": "Edible vegetables and certain roots and tubers",
  "08": "Edible fruit and nuts; Peel of citrus fruit or melons",
  "09": "Coffee, tea, mate and spices",
  "10": "Cereals",
  "11": "Products of the milling industry; Malt; Starches; Inulin; Wheat gluten",
  "12": "Oil seeds and oleaginous fruits; Miscellaneous grains, seeds and fruit; Industrial or medicinal plants; Straw and fodder",
  "13": "Lac; Gums, resins and other vegetable saps and extracts",
  "14": "Vegetable plaiting materials; Vegetable products not elsewhere specified or included",
  "15": "Animal or vegetable fats and oils and their cleavage products; Prepared edible fats; Animal or vegetable waxes",
  "16": "Preparations of meat, of fish or of crustaceans, molluscs or other aquatic invertebrates",
  "17": "Sugars and sugar confectionery",
  "18": "Cocoa and cocoa preparations",
  "19": "Preparations of cereals, flour, starch or milk; Pastrycooks' products",
  "20": "Preparations of vegetables, fruit, nuts or other parts of plants",
  "21": "Miscellaneous edible preparations",
  "22": "Beverages, spirits and vinegar",
  "23": "Residues and waste from the food industries; Prepared animal fodder",
  "24": "Tobacco and manufactured tobacco substitutes",
  "25": "Salt; Sulphur; Earths and stone; Plastering materials, lime and cement",
  "26": "Ores, slag and ash",
  "27": "Mineral fuels, mineral oils and products of their distillation; Bituminous substances; Mineral waxes",
  "28": "Inorganic chemicals; Organic or inorganic compounds of precious metals, of rare-earth metals, of radioactive elements or of isotopes",
  "29": "Organic chemicals",
  "30": "Pharmaceutical products",
  "31": "Fertilisers",
  "32": "Tanning or dyeing extracts; Tannins and their derivatives; Dyes, pigments and other colouring matter; Paints and varnishes; Putty and other mastics; Inks",
  "33": "Essential oils and resinoids; Perfumery, cosmetic or toilet preparations",
  "34": "Soap, organic surface-active agents, washing preparations, lubricating preparations, artificial waxes, prepared waxes, polishing or scouring preparations, candles and similar articles, modelling pastes, ‘dental waxes’ and dental preparations with a basis of plaster",
  "35": "Albuminoidal substances; Modified starches; Glues; Enzymes",
  "36": "Explosives; Pyrotechnic products; Matches; Pyrophoric alloys; Certain combustible preparations",
  "37": "Photographic or cinematographic goods",
  "38": "Miscellaneous chemical products",
  "39": "Plastics and articles thereof",
  "40": "Rubber and articles thereof",
  "41": "Raw hides and skins (other than furskins) and leather",
  "42": "Articles of leather; Saddlery and harness; Travel goods, handbags and similar containers; Articles of animal gut (other than silkworm gut)",
  "43": "Furskins and artificial fur; Manufactures thereof",
  "44": "Wood and articles of wood; Wood charcoal",
  "45": "Cork and articles of cork",
  "46": "Manufactures of straw, of esparto or of other plaiting materials; Basketware and wickerwork",
  "47": "Pulp of wood or of other fibrous cellulosic material; Recovered (waste and scrap) paper or paperboard",
  "48": "Paper and paperboard; Articles of paper pulp, of paper or of paperboard",
  "49": "Printed books, newspapers, pictures and other products of the printing industry; Manuscripts, typescripts and plans",
  "50": "Silk",
  "51": "Wool, fine or coarse animal hair; Horsehair yarn and woven fabric",
  "52": "Cotton",
  "53": "Other vegetable textile fibres; Paper yarn and woven fabrics of paper yarn",
  "54": "Man-made filaments; Strip and the like of man-made textile materials",
  "55": "Man-made staple fibres",
  "56": "Wadding, felt and nonwovens; Special yarns; Twine, cordage, ropes and cables and articles thereof",
  "57": "Carpets and other textile floor coverings",
  "58": "Special woven fabrics; Tufted textile fabrics; Lace; Tapestries; Trimmings; Embroidery",
  "59": "Impregnated, coated, covered or laminated textile fabrics; Textile articles of a kind suitable for industrial use",
  "60": "Knitted or crocheted fabrics",
  "61": "Articles of apparel and clothing accessories, knitted or crocheted",
  "62": "Articles of apparel and clothing accessories, not knitted or crocheted",
  "63": "Other made-up textile articles; Sets; Worn clothing and worn textile articles; Rags",
  "64": "Footwear, gaiters and the like; Parts of such articles",
  "65": "Headgear and parts thereof",
  "66": "Umbrellas, sun umbrellas, walking sticks, seat-sticks, whips, riding-crops and parts thereof",
  "67": "Prepared feathers and down and articles made of feathers or of down; Artificial flowers; Articles of human hair",
  "68": "Articles of stone, plaster, cement, asbestos, mica or similar materials",
  "69": "Ceramic products",
  "70": "Glass and glassware",
  "71": "Natural or cultured pearls, precious or semi-precious stones, precious metals, metals clad with precious metal, and articles thereof; Imitation jewellery; Coin",
  "72": "Iron and steel",
  "73": "Articles of iron or steel",
  "74": "Copper and articles thereof",
  "75": "Nickel and articles thereof",
  "76": "Aluminium and articles thereof",
  "78": "Lead and articles thereof",
  "79": "Zinc and articles thereof",
  "80": "Tin and articles thereof",
  "81": "Other base metals; Cermets; Articles thereof",
  "82": "Tools, implements, cutlery, spoons and forks, of base metal; Parts thereof of base metal",
  "83": "Miscellaneous articles of base metal",
  "84": "Nuclear reactors, boilers, machinery and mechanical appliances; Parts thereof",
  "85": "Electrical machinery and equipment and parts thereof; Sound recorders and reproducers, television image and sound recorders and reproducers, and parts and accessories of such articles",
  "86": "Railway or tramway locomotives, rolling stock and parts thereof; Railway or tramway track fixtures and fittings and parts thereof; Mechanical (including electromechanical) traffic signalling equipment of all kinds",
  "87": "Vehicles other than railway or tramway rolling stock, and parts and accessories thereof",
  "88": "Aircraft, spacecraft, and parts thereof",
  "89": "Ships, boats and floating structures",
  "90": "Optical, photographic, cinematographic, measuring, checking, precision, medical or surgical instruments and apparatus; Parts and accessories thereof",
  "91": "Clocks and watches and parts thereof",
  "92": "Musical instruments; Parts and accessories of such articles",
  "93": "Arms and ammunition; Parts and accessories thereof",
  "94": "Furniture; Bedding, mattresses, mattress supports, cushions and similar stuffed furnishings; Lamps and lighting fittings, not elsewhere specified or included; Illuminated signs, illuminated nameplates and the like; Prefabricated buildings",
  "95": "Toys, games and sports requisites; Parts and accessories thereof",
  "96": "Miscellaneous manufactured articles",
  "97": "Works of art, collectors' pieces and antiques",
  "99": "Other products",
};
