/**
 * Eurostat geonomenclature 2-letter partner code → English country name, for
 * every real territory that appears in raw_comext_imports. COMEXT's SDMX feed
 * is code-only; this is the read-time map the sync spec deferred.
 *
 * Source: codes are `SELECT DISTINCT partner_code FROM raw_comext_imports`;
 * names are Eurostat codelist CXT_FREE_ISO (the DS-045409 `partner`
 * dimension), cleaned to short common forms. Aggregates (EXT/INT_EU27_2020)
 * and the stores-and-provisions / not-specified pseudo-codes
 * (QP/QR/QV/QW/QY/QZ) are deliberately absent — this map doubles as the
 * chart's country allowlist, so anything not here is dropped from the
 * aggregation.
 *
 * Regenerate when heading totals drift below the agridata portal's: re-pull
 * the distinct codes, diff against the keys here, name any newcomer.
 */
export const COMEXT_PARTNER_NAMES: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AG: "Antigua and Barbuda",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BG: "Bulgaria",
  BH: "Bahrain",
  BJ: "Benin",
  BN: "Brunei",
  BO: "Bolivia",
  BR: "Brazil",
  BY: "Belarus",
  CA: "Canada",
  CD: "Democratic Republic of the Congo",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Côte d’Ivoire",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DK: "Denmark",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GE: "Georgia",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GR: "Greece",
  GT: "Guatemala",
  GY: "Guyana",
  HK: "Hong Kong",
  HN: "Honduras",
  HR: "Croatia",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KR: "South Korea",
  KW: "Kuwait",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MD: "Moldova",
  ME: "Montenegro",
  MG: "Madagascar",
  MK: "North Macedonia",
  MN: "Mongolia",
  MR: "Mauritania",
  MT: "Malta",
  MU: "Mauritius",
  MX: "Mexico",
  MY: "Malaysia",
  NC: "New Caledonia",
  NE: "Niger",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PT: "Portugal",
  PY: "Paraguay",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  SA: "Saudi Arabia",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SV: "El Salvador",
  SY: "Syria",
  TD: "Chad",
  TH: "Thailand",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  UA: "Ukraine",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  XK: "Kosovo",
  XS: "Serbia",
  YE: "Yemen",
  ZA: "South Africa",
  ZM: "Zambia",
};
